// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLG57S2Wai9pHrE-PY9lFwmbLs9hu7VQ',
    appId: '1:541530694671:web:a5e7890ae566b641a86f7a',
    messagingSenderId: '541530694671',
    projectId: 'medical-13dde',
    authDomain: 'medical-13dde.firebaseapp.com',
    storageBucket: 'medical-13dde.firebasestorage.app',
    measurementId: 'G-N8BE9T1PL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCI21cB2Do-1pfOmPg2vsNeYF2ww4GgU0',
    appId: '1:541530694671:android:72daa8b6386fb46ba86f7a',
    messagingSenderId: '541530694671',
    projectId: 'medical-13dde',
    storageBucket: 'medical-13dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YhCmwp4qSIJPJKWoCRDM6sVvxhs91pk',
    appId: '1:541530694671:ios:372dd841454e76c6a86f7a',
    messagingSenderId: '541530694671',
    projectId: 'medical-13dde',
    storageBucket: 'medical-13dde.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YhCmwp4qSIJPJKWoCRDM6sVvxhs91pk',
    appId: '1:541530694671:ios:372dd841454e76c6a86f7a',
    messagingSenderId: '541530694671',
    projectId: 'medical-13dde',
    storageBucket: 'medical-13dde.firebasestorage.app',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLG57S2Wai9pHrE-PY9lFwmbLs9hu7VQ',
    appId: '1:541530694671:web:57a1c109b4095bd9a86f7a',
    messagingSenderId: '541530694671',
    projectId: 'medical-13dde',
    authDomain: 'medical-13dde.firebaseapp.com',
    storageBucket: 'medical-13dde.firebasestorage.app',
    measurementId: 'G-6VXM8CVQCF',
  );
}
